# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: "Beyond results: Paving the way for the use of process data"
description: "Workshop on analyzing log file and process data from international large-scale assessments in education - IEA / DIPF / ZIB  - 17-19 June 2020"
github_username: kroehne

# Email and twitter are optional:
email:  
twitter_username:  

# OPTIONAL: override baseurl and url if using a custom domain
url: "https://beyond-results.com/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

# you can comment the below line out if your repo name is not different than your baseurl
github_repo: "BeyondResults"

# Set this to true to get LaTeX math equation support
use_math: 

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# If you want to link only specific pages in your header, uncomment 
# this and add the path to the pages in order as they should show up 
header_pages: 
 - Home
 - Agenda.md
 - frankfurt2020/Frankfurt2020.md 
 - About.md

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-relative-links
  - jekyll-seo-tag

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
